taches_index:
    path:     /
    defaults: { _controller: "tacheBundle:Taches:index" }
    methods:  GET

taches_show:
    path:     /{idTache}/show
    defaults: { _controller: "tacheBundle:Taches:show" }
    methods:  GET

taches_new:
    path:     /new
    defaults: { _controller: "tacheBundle:Taches:new" }
    methods:  [GET, POST]

taches_edit:
    path:     /{idTache}/edit
    defaults: { _controller: "tacheBundle:Taches:edit" }
    methods:  [GET, POST]

taches_delete:
    path:     /{idTache}/delete
    defaults: { _controller: "tacheBundle:Taches:delete" }
    methods:  DELETE
